### ISSUE TITLE
Problem with .dcd & .pdb files

### ISSUE THREAD

**Issue by ucbecla** [fazekaszs/loco_hd#1]
Hi,

I am trying to run this program using a combination of a .dcd trajectory file with a matching .pdb file.

This is the run log I get:

"Loading python3/3.11
  Loading requirement: openssl/1.1.1u python/3.11.4
    openblas/0.3.7-serial/gnu-4.9.2
Calculating the time-dependency of residue LoCoHD scores!
99.8% at time 732 ps. ETA: 0.6 s...
Calculations done!
Calculating bimodalities!
Calculating and plotting LoCoHD principal components...
Traceback (most recent call last):
  File "/lustre/scratch/scratch/ucbecla/B2GPI/LoCoHD.py", line 359, in <module>
    main()
  File "/lustre/scratch/scratch/ucbecla/B2GPI/LoCoHD.py", line 349, in main
    plot_pca(x_values, all_points)
  File "/lustre/scratch/scratch/ucbecla/B2GPI/LoCoHD.py", line 261, in plot_pca
    principal_comp = pca.fit_transform(all_points[1:])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/scratch/scratch/ucbecla/B2GPI/DIR/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/scratch/scratch/ucbecla/B2GPI/DIR/lib/python3.11/site-packages/sklearn/base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/scratch/scratch/ucbecla/B2GPI/DIR/lib/python3.11/site-packages/sklearn/decomposition/_pca.py", line 474, in fit_transform
    U, S, _, X, x_is_centered, xp = self._fit(X)
                                    ^^^^^^^^^^^^
  File "/lustre/scratch/scratch/ucbecla/B2GPI/DIR/lib/python3.11/site-packages/sklearn/decomposition/_pca.py", line 511, in _fit
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/lustre/scratch/scratch/ucbecla/B2GPI/DIR/lib/python3.11/site-packages/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre/scratch/scratch/ucbecla/B2GPI/DIR/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1091, in check_array
    raise ValueError(
ValueError: Found array with 0 feature(s) (shape=(599, 0)) while a minimum of 1 is required by PCA."

When I remove the plot_pca(x_values, all_points) line, the output of the b-factor coloured pdb file has 0 for every residue.

Could this be an error with the format or should it work with .pdb & .dcd files ?
Do you know where the error might come from ?

Cheers,
Christophe

**Comment by fazekaszs** [comment]
Hi Christophe! It appears that somehow the `all_points` array, which is supposed to be of the shape `(# of frames, # of anchor pairs)`  has a size of 0 along the second axis (since the error says shape=(599, 0)). This is a strange behavior, since this only supposed to happen if the anchor index pair list (the variable named `anchors` in the original code) is empty. Here are some of my questions:

- Can you use a debugger (or simply printing) to check if this is the case (i.e. there are no anchor index pairs)?
- Can you check the `pra_templates`/`prim_atoms` variables and the `lchd_scores` results for some of the frames too? 
- Also, can you specify me which primitive typing scheme are you using (the name of the .json file)?
- Did you change anything on the `prat_to_pra` function?

The 0 b-factor output pdb is understandable if the `all_points` array has a 0 size second axis, since the `tempfactors` variable will be an empty array (somehow `np.std(all_points[1:], axis=0)` is an empty array if the axis is specified, but NaN, if it isn't). This way, the code won't enter the for-loop that sets the temperature factors of the residues.

I don't think that the .dcd format is at fault here, it will be something else.

**Comment by ucbecla** [comment]
Hi,
Thank you for your quick reply !

I'm afraid I am not great at Python so I got GPT to implement some of the debugging steps. This is the output

"Calculating the time-dependency of residue LoCoHD scores!
anchors: []
Frame 0: pra_templates: [PrimitiveAtomTemplate(primitive_type='O_neu', coordinates=array([21.431559 , 19.475874 ,  6.9753537], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['O'])), PrimitiveAtomTemplate(primitive_type='N_neu', coordinates=array([20.01002  , 21.579618 ,  5.3338304], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['N'])), PrimitiveAtomTemplate(primitive_type='C_ali', coordinates=array([19.384398, 20.684753,  6.438263], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['CA'])), PrimitiveAtomTemplate(primitive_type='C_ali', coordinates=array([20.3676   , 19.991789 ,  7.3505187], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['C'])), PrimitiveAtomTemplate(primitive_type='O_neu', coordinates=array([20.89065 , 17.390413, 11.092613], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 1, ' ')), source_residue_name='ARG', source_atom=['O']))]
Frame 0: prim_atoms: [<builtins.PrimitiveAtom object at 0x2af57fdd6eb0>, <builtins.PrimitiveAtom object at 0x2af57fdd6f70>, <builtins.PrimitiveAtom object at 0x2af57fdd6e50>, <builtins.PrimitiveAtom object at 0x2af57fdd6df0>, <builtins.PrimitiveAtom object at 0x2af57fdd6d90>]
Frame 0: lchd_scores: []

0.0% at time 0 ps. ETA: 329.8 s.Frame 1: pra_templates: [PrimitiveAtomTemplate(primitive_type='O_neu', coordinates=array([26.375265, 16.48037 , 10.11088 ], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['O'])), PrimitiveAtomTemplate(primitive_type='N_neu', coordinates=array([27.261063 , 17.16885  ,  7.6098223], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['N'])), PrimitiveAtomTemplate(primitive_type='C_ali', coordinates=array([26.3739  , 18.136135,  8.365753], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['CA'])), PrimitiveAtomTemplate(primitive_type='C_ali', coordinates=array([25.774294, 17.392868,  9.521323], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['C'])), PrimitiveAtomTemplate(primitive_type='O_neu', coordinates=array([21.803705, 18.233454, 10.232057], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 1, ' ')), source_residue_name='ARG', source_atom=['O']))]
Frame 1: prim_atoms: [<builtins.PrimitiveAtom object at 0x2af57f9a9ad0>, <builtins.PrimitiveAtom object at 0x2af57fb3e250>, <builtins.PrimitiveAtom object at 0x2af57fb3e2b0>, <builtins.PrimitiveAtom object at 0x2af57fb3e370>, <builtins.PrimitiveAtom object at 0x2af57fb3e430>]
Frame 1: lchd_scores: []

0.2% at time 1 ps. ETA: 348.1 s.Frame 2: pra_templates: [PrimitiveAtomTemplate(primitive_type='O_neu', coordinates=array([26.887566, 16.049685, 11.125685], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['O'])), PrimitiveAtomTemplate(primitive_type='N_neu', coordinates=array([28.325758, 17.498901,  8.897366], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['N'])), PrimitiveAtomTemplate(primitive_type='C_ali', coordinates=array([26.99443 , 17.922644,  9.551447], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['CA'])), PrimitiveAtomTemplate(primitive_type='C_ali', coordinates=array([26.376785, 17.081675, 10.642605], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['C'])), PrimitiveAtomTemplate(primitive_type='O_neu', coordinates=array([22.730625, 18.135736, 11.254849], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 1, ' ')), source_residue_name='ARG', source_atom=['O']))]
Frame 2: prim_atoms: [<builtins.PrimitiveAtom object at 0x2af57fb3df50>, <builtins.PrimitiveAtom object at 0x2af57fb3e010>, <builtins.PrimitiveAtom object at 0x2af57fb3e070>, <builtins.PrimitiveAtom object at 0x2af57fb3dfb0>, <builtins.PrimitiveAtom object at 0x2af57fb3e0d0>]
Frame 2: lchd_scores: []

0.3% at time 2 ps. ETA: 337.8 s.Frame 3: pra_templates: [PrimitiveAtomTemplate(primitive_type='O_neu', coordinates=array([26.316776, 17.485693, 12.676594], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['O'])), PrimitiveAtomTemplate(primitive_type='N_neu', coordinates=array([27.893732, 19.888706, 12.137186], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['N'])), PrimitiveAtomTemplate(primitive_type='C_ali', coordinates=array([26.700932, 19.529478, 11.373068], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['CA'])), PrimitiveAtomTemplate(primitive_type='C_ali', coordinates=array([25.834808, 18.447966, 12.098959], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 0, ' ')), source_residue_name='GLY', source_atom=['C'])), PrimitiveAtomTemplate(primitive_type='O_neu', coordinates=array([22.06659  , 18.348768 , 10.8935995], dtype=float32), atom_source=PrimitiveAtomSource(source_residue=('prot', 0, 'A', (' ', 1, ' ')), source_residue_name='ARG', source_atom=['O']))]
Frame 3: prim_atoms: [<builtins.PrimitiveAtom object at 0x2af57fa7eeb0>, <builtins.PrimitiveAtom object at 0x2af57fb57f30>, <builtins.PrimitiveAtom object at 0x2af57fb617d0>, <builtins.PrimitiveAtom object at 0x2af57fb62af0>, <builtins.PrimitiveAtom object at 0x2af57fb63f30>]
Frame 3: lchd_scores: []

... through to frame 600

Calculations done!
all_points shape: (600, 0)
Error: all_points array has a size of 0 along the second axis
Calculating bimodalities!"

I am using the all_atom json file. Script is completely unchanged except for the file locations.

Best,
Christophe

**Comment by fazekaszs** [comment]
This reaffirms my initial guess that you have no anchor index pairs, since the `anchors` variable is an empty list.

First of all, if you are using `all_atom.config.json` then this primitive typing scheme will not contain Centroid primitive types, which are the only ones selected as anchors in the code. This selection happens in this line btw:
`anchors = [(idx, idx) for idx, prat in enumerate(pra_templates_start) if prat.primitive_type == "Cent"]`. Since the `if` at the end will never be satisfied, this will result in an empty list. However, it is an easy problem to solve: simply switch to the `all_atom_with_centroid.config.json` file (this __will__ contain the Centroids too).

What's more concerning for me is that your `pra_templates` and `prim_atoms` variables only contain 5 primitive atoms (4 from a glycine, 1 from an arginine). Are these the full lists you pasted here, or did you shorten them down? These lists are usually at least as long as many heavy atoms the simulated system contains. If you see less atoms than the number of atoms in your simulated system, then something goes wrong at the primitive atom assignment step in the `MDPrimitiveAssigner` object's `assign_from_universe` function.

Some more questions, if you don't mind:

- I can already guess the answer to this, but I have to ask: does your system contain only 5 atoms?
- Does your simulation contain unnatural/noncanonical amino acids? Because the current primitive type assigners cannot handle those and they won't be considered during the calculation. Residues should be also correctly named in the pdb file!
- Do you have more than one chain in the simulation? I have to admit, the `assign_from_universe` function is a bit sloppily written and assigns chain "A" for every residue. For the MD example in our article it was not a problem, since residues were numbered between 1-172 in chain "A" and 173-344 in chain "B" and this way the chain information was not lost even after assigning "A" for every residue. However, if your simulated system is multi-chain and the residue numbers overlap, this can lead to problems.

**Comment by ucbecla** [comment]
Hello;

The script was written to only output the first 5 atoms as a way of checking where the fault was coming from; but yes I do have more than 5 atoms ! There are no unnatural amino acids; and all in one single chain.

I tried again with the all_atom_with_centroid out of curiosity before this reply and the program now runs normally 👍

Thanks for your help; and for this method; I look forward to investigating the results in more detail and comparing to other measures like SASA & rmsf !

Best,
Christophe

**Comment by fazekaszs** [comment]
This is great! I'm glad I was able to help! Good luck with your research. I'm closing the issue.
